"""Central config loader: settings.yaml, profile.yaml, search_terms.yaml, .env."""
from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent


def _load_env() -> None:
    env_file = ROOT / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                os.environ.setdefault(key.strip(), val.strip())


@lru_cache(maxsize=None)
def load(name: str) -> dict:
    _load_env()
    path = ROOT / "config" / f"{name}.yaml"
    data = yaml.safe_load(path.read_text()) or {}
    return data


def settings() -> dict:
    return load("settings")


def profile() -> dict:
    return load("profile")


def search_terms() -> dict:
    return load("search_terms")


def recipes() -> dict:
    return load("recipes").get("recipes") or {}


def notion_ids() -> dict:
    """IDs generated by upgrade_notion_schema.py (metrics DB, digest pages)."""
    path = ROOT / settings()["notion"]["generated_ids_file"]
    if path.exists():
        return yaml.safe_load(path.read_text()) or {}
    return {}


def notion_token() -> str:
    _load_env()
    token = os.environ.get("NOTION_TOKEN")
    if not token:
        raise RuntimeError("NOTION_TOKEN not set (add it to .env)")
    return token


def anthropic_key() -> str | None:
    _load_env()
    return os.environ.get("ANTHROPIC_API_KEY")


def openai_key() -> str | None:
    _load_env()
    return os.environ.get("OPENAI_API_KEY")


def adzuna_credentials() -> tuple[str | None, str | None]:
    _load_env()
    return os.environ.get("ADZUNA_APP_ID"), os.environ.get("ADZUNA_APP_KEY")
